version: "3.5"

services:
  sum:
    build:
      context: ./sum
    restart: unless-stopped
    container_name: sum
    image: skn1942/math-o-sum
    ports:
      - "5000:5000"
      # networks:
      #   test-net:
      # ipv4_address: 172.16.238.10
    volumes:
      - "./sum:/app"

  subtract:
    build:
      context: ./subtract
    restart: unless-stopped
    container_name: subtract
    image: skn1942/math-o-subtract
    ports:
      - "5001:5001"
      # networks:
      #   test-net:
      # ipv4_address: 172.16.238.10
    volumes:
      - ./subtract:/app

  multiply:
    build:
      context: ./multiply
    restart: unless-stopped
    container_name: multiply
    image: skn1942/math-o-multiply
    ports:
      - "5002:5002"
      # networks:
      #   test-net:
      # ipv4_address: 172.16.238.10
    volumes:
      - "./multiply:/app"

  division:
    build:
      context: ./division
    restart: unless-stopped
    container_name: division
    image: skn1942/math-o-division
    ports:
      - "5003:5003"
      # networks:
      #   test-net:
      # ipv4_address: 172.16.238.10
    volumes:
      - "./division:/app"

  power:
    build:
      context: ./power
    restart: unless-stopped
    container_name: power
    image: skn1942/math-o-power
    ports:
      - "5004:5004"
      # networks:
      #   test-net:
      # ipv4_address: 172.16.238.10
    volumes:
      - "./power:/app"

  sqrt:
    build:
      context: ./sqrt
    restart: unless-stopped
    container_name: sqrt
    image: skn1942/math-o-sqrt
    ports:
      - "5005:5005"
      # networks:
      #   test-net:
      # ipv4_address: 172.16.238.10
    volumes:
      - "./sqrt:/app"

  orchestrator:
    build:
      context: ./orchestrator
    restart: unless-stopped
    container_name: orchestrator
    image: skn1942/math-o-orchestrator
    ports:
      - "5006:5006"
      # networks:
      #   test-net:
      # ipv4_address: 172.16.238.10
    volumes:
      - "./orchestrator:/app"
    depends_on:
      - sqrt
      - power
      - multiply
      - division
      - subtract
      - sum

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # networks:
    #   test-net:
    #     # ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - ./monitoring/config.monitoring
    # networks:
    #   test-net:
    #     # ipv4_address: 172.16.238.12

networks:
  test-net:
    name: test-net
    driver: bridge
    ipam:
      driver: default
      # config:
      #   - subnet: 172.16.238.0/24

volumes:
  reper_db:
