name: tests-orchestrator

on: 
  pull_request:
    paths:
      - 'orchestrator/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - run : cd orchestrator && pip install -r requirements.txt && pytest
